---
- hosts: all
  become: true
  vars:
     package0: python3-apt
     package01: python-apt-common
     package1: clamav
     package2: clamav-daemon
  tasks:
     - name: Install Package python3-apt
       apt: name={{ package0 }} state=latest
     - name: Install Package python-apt-common
       apt: name={{ package01 }} state=latest
     - name: Install Package ClamAV
       apt: name={{ package1 }} state=latest
     - name: Install Package ClamAv-Daemon
       apt: name={{ package2 }} state=latest
