---
- hosts: all
  become: true
  vars:
     package1: clamav
     package2: clamav-daemon
  tasks:
     - name: Install Package ClamAV
       apt: name={{ package1 }} state=latest
     - name: Install Package ClamAv-Daemon
       apt: name={{ package2 }} state=latest
